env:
  browser: true
  es6: true
  node: true
  mocha: true
extends:
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "prettier"
rules:
  "prettier/prettier": "error"
